name: Build main

on:
  push:
    branches:
    - main
    
permissions:
  id-token: write
  contents: read
  
env: 
  AZURE_SUBSCRIPTION_ID: ${{ secrets.AZURE_SUBSCRIPTION_ID }}
  AZURE_CLIENT_ID: ${{ secrets.AZURE_SUBSCRIPTION_ID }}

jobs:
  trigger:
    name: trigger
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Setup Node.js environment
        uses: actions/setup-node@v4.0.2
        with: 
          node-version: 18.12.0

      - name: install dependencies
        run: |
          npm install
          ls
          pwd

      - name: Upload coverage to Codecov
        uses: codecov/codecov-action@v1

      - name: Build
        run: npm run build

      - name: Azure Login
        uses: Azure/login@v2.0.0
        with:
          client-id: ${{ secrets.AZURE_CLIENT_ID }}
          tenant-id: ${{ secrets.AZURE_TENANT_ID }}
          subscription-id: ${{ secrets.AZURE_SUBSCRIPTION_ID }}

      - name: Deploy
        uses: Azure/webapps-deploy@v3.0.0
        with:
          app-name: 'currency-front'
          package: './src/App.tsx'
